apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- name: '*'
  newName: quay.io/kbelwaer/express-sample
  newTag: f011dea00b97bbd5e4b29c2c8b4565fada037857
