apiVersion: v1
kind: ServiceAccount
metadata:
  name: khouloud-belwaer-service
secrets: 
  - name: kbelwaer-kustomize-pipeline-pull-secret

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer
rules:
- resources:
  - deployments
  apiGroups:
  - apps
  verbs:
  - get
  - create
  - list
  - patch
  - watch
- resources:
  - routes
  apiGroups:
  - route.openshift.io
  verbs:
  - get
  - create
  - patch
- resources:
  - services
  apiGroups:
  - ""
  verbs:
  - get
  - patch
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer
roleRef:
  name: deployer
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: khouloud-belwaer-service
  kind: ServiceAccount

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-receiver

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webhook-receiver
rules:
  - resources:
      - eventlisteners
      - triggerbindings
      - triggertemplates
    apiGroups:
      - triggers.tekton.dev
    verbs:
      - get
  - resources:
      - pipelineruns
      - pipelineresources
    apiGroups:
      - tekton.dev
    verbs:
      - create
  - resources:
      - configmaps
    apiGroups:
      - ""
    verbs:
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webhook-receiver
roleRef:
  name: webhook-receiver
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: webhook-receiver
    kind: ServiceAccount