apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: webhook-receiver
spec:
  serviceAccountName: webhook-receiver
  triggers:
  - template:
      name: webhook-receiver
    bindings:
    - ref: webhook-receiver
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: webhook-receiver
spec:
  params:
  - name: source-repo
    description: Source code repository
  - name: sha
    description: Precise SHA of the commit to build
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: express-sample-app-
    spec:
      serviceAccountName: khouloud-belwaer-service
      params:
      - name: app-name
        value: express-sample-app
      - name: image-repo
        value: quay.io/kbelwaer/express-sample
      - name: source-repo
        value: $(tt.params.source-repo)
      - name: sha
        value: $(tt.params.sha)
      pipelineRef:
        name: nodejs
      workspaces:
      - name: pipeline-shared-data
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 1Gi
            accessModes:
            - ReadWriteOnce
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: webhook-receiver
spec:
  params:
  - name: source-repo
    value: $(body.repository.url)
  - name: sha
    value: $(body.head_commit.id)

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: webhook-receiver
spec:
  port:
    targetPort: 8080
  to:
    name: el-webhook-receiver
    kind: Service
    weight: 100